from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    Import: Any = None
    env: Any = {}

Import("env")  # type: ignore

project_dir = Path(env.get("PROJECT_DIR"))
source_file = project_dir / "embedded_resources" / "mali_portal" / "mali_lab.html"
header_file = project_dir / "include" / "maliPortalTemplate.h"
max_template_bytes = 24 * 1024


def render_header(content: bytes) -> str:
    rows = []
    for offset in range(0, len(content), 16):
        chunk = ", ".join(f"0x{value:02X}" for value in content[offset : offset + 16])
        rows.append(f"    {chunk},")

    byte_rows = "\n".join(rows)
    return f"""#pragma once

#include <Arduino.h>

// AUTOGENERATED. Edit embedded_resources/mali_portal/mali_lab.html instead.
static const uint8_t mali_lab_html[] PROGMEM = {{
{byte_rows}
}};

static constexpr size_t mali_lab_html_size = sizeof(mali_lab_html);
"""


if not source_file.is_file():
    raise FileNotFoundError(f"Mali Portal template not found: {source_file}")

source_content = source_file.read_bytes()
if not source_content or len(source_content) > max_template_bytes:
    raise ValueError("mali_lab.html must contain between 1 byte and 24 KiB")

generated_content = render_header(source_content)
header_file.parent.mkdir(parents=True, exist_ok=True)
if not header_file.is_file() or header_file.read_text(encoding="utf-8") != generated_content:
    with header_file.open("w", encoding="utf-8", newline="\n") as generated_header:
        generated_header.write(generated_content)
    print(f"[MALI PORTAL] Embedded {len(source_content)} bytes from {source_file.name}")
else:
    print("[MALI PORTAL] Template header is up to date.")
