"""Generate the compile-time PT-BR catalog and migrate reviewed UI call sites."""
import hashlib, json, re, sys
from pathlib import Path
from review_catalog import ROOT, scan

catalog={}
for line in (ROOT/'src/core/ui/pt_br.tsv').read_text(encoding='utf-8').splitlines():
    if not line or line.startswith('#'): continue
    english, portuguese=line.split('\t',1)
    assert english not in catalog, english
    # Keep printf argument types and ordering, escapes and protocols intact.
    fmt=r'%(?:[-+ #0]*\d*(?:\.\d+)?(?:ll|l|z)?[diuoxXfFeEgGcs%])'
    assert re.findall(fmt,english)==re.findall(fmt,portuguese),(english,portuguese)
    stem=re.sub(r'[^a-z0-9]+','_',english.lower()).strip('_')[:44]
    if not stem or stem[0].isdigit(): stem='text_'+stem
    catalog[english]=(stem+'_'+hashlib.sha1(english.encode()).hexdigest()[:6],portuguese)
header=['#pragma once','// Generated by tests/mali_ui/migrate_locale.py from pt_br.tsv.',
        '// ASCII spelling on the TFT matches its built-in fixed bitmap font.',
        '// No runtime lookup, heap allocation, or changes to external data.', 'namespace MaliText {']
for english,(name,value) in sorted(catalog.items()):
    header.append(f'inline constexpr char {name}[] = "{value}";')
header.append('} // namespace MaliText\n')
target=ROOT/'src/core/ui/PtBr.h'
generated='\n'.join(header)
if not target.exists() or target.read_text(encoding='utf-8') != generated:
    target.write_text(generated,encoding='utf-8')

if __name__=='__main__':
    if '--apply' not in sys.argv:
        print(f'{len(catalog)} compile-time PT-BR texts generated; source migration requires --apply')
        raise SystemExit(0)
    changed=[]
    for folder in ['src','include']:
        for path in (ROOT/folder).rglob('*'):
            if path.suffix not in ['.cpp','.h'] or path.name in ['PtBr.h','webFiles.h'] or 'protocols' in path.parts: continue
            source=path.read_text(encoding='utf-8-sig')
            relative=path.relative_to(ROOT).as_posix()
            # These files keep UI labels/messages separate from machine-format keys.
            reviewed=relative.startswith('src/mali_tools/') or relative=='src/core/ui/MaliUI.cpp'
            edits=[]
            for row in scan(path):
                raw=row['text']
                extra_ui = relative == 'src/core/wifi/CounterWebApi.cpp' or (relative == 'src/modules/ble/BLE_Suite.cpp' and row['start'] > source.find('void showWelcomeScreen() {'))
                if raw not in catalog or not (row['ui'] or reviewed or extra_ui): continue
                before=source[max(0,row['start']-100):row['start']]
                after=source[row['end']:row['end']+100]
                # Do not alter DuckyScript instruction/keyboard lookup tables.
                if 'ducky_typer' in relative and not re.search(r'(?:tft\.|display|keyboard)',before): continue
                if re.search(r'(?:F|PSTR)\(\s*$',before): continue
                if re.search(r'"\s*$',before) or re.match(r'\s*"',after): continue
                edits.append((row['start'],row['end'],'MaliText::'+catalog[raw][0]))
            if not edits: continue
            for start,end,text in reversed(edits): source=source[:start]+text+source[end:]
            if '#include "core/ui/PtBr.h"' not in source: source='#include "core/ui/PtBr.h"\n'+source
            path.write_text(source,encoding='utf-8')
            changed.append({'path':relative,'literals':len(edits)})
    (ROOT/'tests/mali_ui/locale-migration.json').write_text(json.dumps(changed,indent=2),encoding='utf-8')
    print(f'{len(catalog)} central texts; {sum(x["literals"] for x in changed)} occurrences in {len(changed)} files')
